version: 1.0.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore C:\projects\Kairos.API\Kairos.API.sln
build:
  verbosity: minimal
artifacts:
- path: Kairos.API/bin/Release/Kairos.API.dll